### ISSUE TITLE
About landmark

### ISSUE THREAD

**Issue by MontaEllis** [DavidBoja/SMPL-Fitting#1]
Nice work! But I wonder how can I get landmark of the scan?

**Comment by DavidBoja** [comment]
Hi, thank you :)
You need to have the landmarks already provided or you can select them manually on the scan. You don't need to provide all the 72 body landmarks as we mention in `landmarks.py`, but you can try and annotate around 20 of them all over the scan body - it should be enough to converge.

There are papers on the topic of finding landmarks on scans, however I don't believe any of them have open-sourced their code unfortunately. Let me know if you find some, I'd also be interested :).
