### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by danielepaolucci1998** [DavidBoja/SMPL-Fitting#2]
Is this code compatible with Windows 11? I keep getting this error: 

RuntimeError: Error building extension 'cd': [1/1] "/link.exe" chamfer_distance.o chamfer_distance.cuda.o /nologo /DLL c10.lib c10_cuda.lib to
rch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\WKS\pythonProject8\lib\site-packages\torch\lib torch
_python.lib "/LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\libs" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\lib\x64" cudart.lib /out:cd.pyd
FAILED: cd.pyd
"/link.exe" chamfer_distance.o chamfer_distance.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda
@at@@YAHXZ torch.lib /LIBPATH:C:\Users\WKS\pythonProject8\lib\site-packages\torch\lib torch_python.lib "/LIBPATH:C:\Program Files\WindowsApps\
PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\libs" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\lib\x64" cudart.lib /out:cd.pyd
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

thx.

**Comment by DavidBoja** [comment]
You're getting issues with  cuda for the chamfer distance submodule. I used the submodule from [here](https://github.com/chrdiller/pyTorchChamferDistance/tree/924e54bec55f8b27f1230545758bc97a1599e799). You can check if there are some issues on the repo already there, but it seems that this is a local problem with your cuda installation.

**Comment by danielepaolucci1998** [comment]
Thx i solved the problem some time ago, re-installing CUDA12.5 and then microsoft visual studio and using a virtual enviroment(withpython3.10) to run the  code.
